#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 0) readonly buffer Positions
{
   vec4 aPositions[];
};

layout(std430, binding = 1) writeonly buffer Results
{
   float aDistances[];
};

layout(push_constant) uniform PushConstants
{
   vec4 vQueryPoint;
   uint nCount;
};

void main ()
{
   uint nIdx = gl_GlobalInvocationID.x;
   if (nIdx < nCount)
   {
      aDistances[nIdx] = distance (aPositions[nIdx].xyz, vQueryPoint.xyz);
   }
}
